/*
2012 ReadSpeaker International B.v.
*/
ReadSpeaker.Common=function(){var n={revision:"6672"},p={onAdapterReady:[],onInit:[],onCoreLoaded:[],onModsLoaded:[],onAfterModsLoaded:[],onAfterExtraModsLoaded:[],onConfigLoaded:[],onConfigSetup:[],onDOMReady:[],onReady:[],onSelectedText:[],onDeselectedText:[],onSettingsInitialized:[],onSettingsChanged:[],onSettingsLoaded:[],onSettingsClosed:[],onDownloadLoaded:[],onFocusIn:[],onFocusOut:[],onUIInitialized:[],onUIBeforePlay:[],onUIAfterPlay:[],onUIPause:[],onUISliderMove:[],onUIStop:[],onUIShowPlayer:[],
onUIClosePlayer:[],onAPIPlay:[],onAPIPause:[],onAPIStop:[],onAPIVolumeUp:[],onAPIVolumeDown:[],onAPIMute:[],onAPIFastForward:[],onAPIRewind:[],onAPISetVolume:[],onAPISetProgress:[],onAPIGetProgress:[],onAPIInitAdapter:[],onAPIReleaseAdapter:[],onAPIReloadAdapter:[],onBeforeSyncInit:[],onAfterSyncInit:[],onBeforeSync:[],onAfterSync:[],onAfterSyncExit:[],onBeforeContentChange:[],onAfterContentChange:[],onBeforeGetAudioLink:[],onBeforeParamsSet:[],onAfterParamsSet:[],onAudioLoadError:[],onVolumeAdjusted:[],
onChunkResume:[]},r={speed:function(a,c){var b=parseInt(c||rspkr.pub.Config.item("general.defaultSpeedValue")||100),d=parseInt(rspkr.pub.Config.item("general.defaultSlowSpeedValue")||b-25),e=parseInt(rspkr.pub.Config.item("general.defaultFastSpeedValue")||b+25);switch(a){case "slow":return d;case "medium":return b;case "fast":return e;default:return b}}},h={audioLink:null,params:{},postContent:"",postLink:null,saveLink:null,selectedHTML:"",selectedText:"",selectedRange:null,sync:"wordsent",syncLink:null,
browser:{name:"",flashVersion:"",version:"",OS:"",html5AudioFormat:"",html5Support:!1,html5Priority:!1,syncContainer:""},setParams:function(a){rspkr.log("[rspkr.c.data.setParams] "+a);if("string"==typeof a){this.params={};var c="",b="",c="",b=a.split("?");rspkr.cfg.item("general.servercall",b[0]);a=b[1].split(/[;&]/);for(var d=0;d<a.length;d++)if((c=a[d].split("="))&&2==c.length){var b=decodeURIComponent(c[0]),e=c[1],c=decodeURIComponent(c[1]);if("url"==b&&!c.length)e=encodeURIComponent(document.location.href);
else if("lang"==b&&2==c.length)for(var f in rspkr.cfg.item("phrases")){if(rspkr.cfg.item("phrases").hasOwnProperty(f)&&c==f.substring(0,2)){e=f;break}}else if("readid"==b||"readclass"==b){for(var c=function(a,b){for(var c=0,d=a.length;c<d;c++)if(this[c]===b)return c;return-1},e=e.split(","),l=[],k=0;k<e.length;k++)-1==c(l,e[k])&&l.push(e[k]);e=l.join(",")}this.params[b]=e}this.params.rsjs_ver=rspkr.getVersion();this.params.synccontainer=this.browser.syncContainer;this.params.url||(this.params.url=
document.location.href);this.params.readid=this.params.readid||"";if(rspkr.c.data.selectedText||rspkr.c.data.selectedHTML)delete this.params.readid,delete this.params.readclass;rspkr.Common.dispatchEvent("onAfterParamsSet")}},setDefaultValues:function(){rspkr.log("[rspkr.c.data.setDefaultValues] Called!");rspkr.Common.data.selectedHTML="";rspkr.Common.data.saveLink=null},setPostContent:function(a){if("string"==typeof a){if("textsel"===a)a=this.selectedHTML;else{var c=[],b=a="";rspkr.hl&&rspkr.hl.Restore.hasMarkup()&&
rspkr.hl.sync.fullCleanUp();var d=[];rspkr.c.data.params.hasOwnProperty("readid")&&rspkr.c.data.params.readid.length&&(d=d.concat(("#"+rspkr.c.data.params.readid.split(",").join(",#")).split(",")));rspkr.c.data.params.hasOwnProperty("readclass")&&rspkr.c.data.params.readclass.length&&(d=d.concat(("."+rspkr.c.data.params.readclass.split(",").join(",.")).split(",")));if(rspkr.cfg.item("general.readidOrder")&&rspkr.cfg.item("general.usePost"))for(b=0;b<d.length;b++){var e=$rs.get(d[b]);$rs.isArray(e)&&
0<e.length?c.concat(e):$rs.isArray(e)||c.push(e)}else c=$rs.get(d.join(","));$rs.isArray(c)||(c=[c]);for(e=0;d=c[e];e++){var f;f=d.nodeName&&"TABLE"==d.nodeName?"TABLE":"DIV";for(var l=d.attributes,k="",u=l.length;u--;)b=l[u],"data-"!==b.name.substr(0,5)&&(k+=" "+b.name+'="'+b.value+'"');a+="<"+f+k+">"+d.innerHTML+"</"+f+">"}c=document.createElement("div");c.innerHTML=a;a=$rs.findIn(c,".rs_skip.rs_preserve");$rs.isArray(a)||(a=[a]);for(b=0;d=a[b];b++)d.innerHTML="";a=c.innerHTML}!0===rspkr.cfg.item("general.parseMathJax")&&
(a=this.parseMathJax(a));this.postContent=m.encode(a)}},parseMathJax:function(a){var c=document.createElement("div"),b,d,e;d=window.MathJax;c.innerHTML=a;if(b=$rs.findIn(c,".MathJax")){a=$rs.findIn(b,".math");$rs.isArray(a)&&0===a.length&&(a=b);a=$rs.isArray(a)?a:[a];for(var f=a.length-1;0<=f;f--)"object"===typeof a[f]&&(e=document.createElement("div"),mjaxObj=d.Hub.getJaxFor(a[f].id),e.innerHTML=mjaxObj.originalText,b=$rs.closest(a[f],"div.MathJax_Display"),$rs.hasClass(a[f],"math")?(a[f].parentNode.parentNode.replaceChild(e,
a[f].parentNode),b&&b.tagName&&b.parentNode.replaceChild(e,b)):b?b.parentNode.replaceChild(e,b):a[f].parentNode.replaceChild(e,a[f]));d=c.getElementsByTagName("script");for(a=d.length-1;0<=a;a--)d[a].type&&"math/mml"===d[a].type&&d[a].parentNode.removeChild(d[a]);return c.innerHTML}return a},setSelectedText:function(a){if(window.getSelection||document.getSelection){var c=function(a,b){if(void 0===b||null===b)b=[];var d=[];try{d=a.document.querySelectorAll("iframe, frame")}catch(e){rspkr.log("Error accessing document"+
e,"3")}for(var f=0;f<d.length;f++)b.push(d[f].contentWindow);for(f=0;f<d.length;f++)c(d[f].contentWindow,b)},b=void 0,d=void 0,e=function(){var a;rspkr.cfg.item("general.iframeReading")?a=window.parent.getSelection():window.getSelection();if(a&&(a.isCollapsed||1>a.rangeCount)){a=[];rspkr.cfg.item("general.iframeReading")?c(window.parent,a):a=[window];for(var b=0;b<a.length;b++){var d=a[b];try{if(0<d.getSelection().rangeCount&&!d.getSelection().isCollapsed)return d.document}catch(e){rspkr.log("error getting document:"+
e,"3")}}}return rspkr.cfg.item("general.iframeReading")?window.parent.document:window.document}();this.selectedText="";rspkr.HL.clientMarkup.selectionDocument=e;if(e.getSelection&&(d=e.getSelection(),!d.isCollapsed&&0<d.rangeCount)){if(d.getRangeAt){var f=d.getRangeAt(0),l=d.getRangeAt(d.rangeCount-1),b=e.createRange();b.setStart(f.startContainer,f.startOffset);b.setEnd(l.endContainer,l.endOffset)}else b=e.createRange(),b.setStart(d.anchorNode,d.anchorOffset),b.setEnd(d.focusNode,d.focusOffset);b?
(DOM=b.cloneContents(),object=e.createElement("div"),object.appendChild(DOM.cloneNode(!0)),this.selectedText=object.innerHTML,this.selectedRange=b):this.selectedText=d}0<this.selectedText.length&&a?g("onSelectedText",window,[a]):g("onDeselectedText",window,["empty"])}else document.selection&&(d=document.selection,this.selectedText=(b=d.createRange())&&b.htmlText&&b.text&&0<b.text.length?b.htmlText:b&&b.text?b.text:"",this.selectedRange=b.duplicate(),rspkr.HL.clientMarkup.selectionDocument=document,
0<this.selectedText.length&&a?g("onSelectedText",window,[a]):g("onDeselectedText",window,["empty"]));rspkr.log("[rspkr.c.setSelectedText] Selected text length is "+this.selectedText.length)},createReadRange:function(a){if(a=document.getElementById(a))if(document.selection&&(9>this.browser.version||9>document.documentMode)){var c=document.body.createTextRange();c.moveToElementText(a);this.selectedRange=c;this.selectedText=c.htmlText}else c=document.createRange(),c.selectNodeContents(a),this.selectedRange=
c,this.selectedText=c.toString()},getParam:function(a){return this.params&&this.params[a]&&void 0!==this.params[a]?this.params[a]:null},getParams:function(){return this.params},getPostContent:function(){return this.postContent},getRestoreContent:function(){return this.restoreContent},getSelectedText:function(){return this.selectedText},getAudioLink:function(a,c){rspkr.devt("onBeforeGetAudioLink",window);c="undefined"!==typeof c?c:rspkr.HL;this.audioLink=null;var b={},d;for(d in this.params)this.params.hasOwnProperty(d)&&
(b[d]=this.params[d]);for(d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);d=r.speed(rspkr.Common.Settings.get("hlspeed"),b.speed?b.speed:void 0);100!=d&&(b.speed=d);(d=rspkr.cfg.item("general.selectionEngine"))&&"newcontent"===d&&b.hasOwnProperty("readid")&&1>this.selectedText.length&&(!document.selection||document.selection&&8<rspkr.Common.data.browser.version&&8<document.documentMode)&&this.createReadRange(b.readid);if(b.readid&&/rslightbox_content/gi.test(b.readid)){0==rs.cfg.item("general.usePost")?(rs.cfg.item("general.usePost",
!0),rspkr.c.addEvent("onSettingsClosed",function(){rs.cfg.item("general.usePost",!1);rs.PlayerAPI.stop()})):rspkr.c.addEvent("onSettingsClosed",function(){rs.PlayerAPI.stop()});var e=function(a){for(var b=function(a,b){return document.defaultView&&document.defaultView.getComputedStyle?document.defaultView.getComputedStyle(a,null)[b]:a.currentStyle?a.currentStyle[b]:a.style[b]},c=0;c<a.childNodes.length;c++){var d=a.childNodes[c],g=d.className&&-1!==d.className.indexOf("rs_skip_always");1!==d.nodeType||
"none"!=b(d,"display")&&"hidden"!=b(d,"visibility")||g?d.title?$rs.addClass(d,"rs_skip_always"):1===d.nodeType&&e(d):$rs.addClass(d,"rs_skip_always")}};e($rs.get("rslightbox_content"))}0<this.selectedText.length||0<this.selectedHTML.length?(0<this.selectedText.length&&c.clientMarkup.preProcess.init(),b.sync="user",b.syncalignuser=rspkr.st.get("hl"),this.setPostContent("textsel"),this.audioLink=q.issuePost(b)):!0===rspkr.cfg.item("general.premarkup")?(b.sync="user",this.setPostContent("nosel"),!0===
rspkr.pub.Config.item("general.usePost")?this.audioLink=q.issuePost(b):this.audioLink=s(b)):!0===rspkr.pub.Config.item("general.usePost")?(b.sync="wordsent",this.setPostContent("nosel"),this.audioLink=q.issuePost(b)):(b.sync="wordsent",this.audioLink=s(b));rspkr.log("[rspkr.c.data.getAudioLink] Audio link: "+this.audioLink);return this.audioLink},setSettingsChanged:function(a,c,b){"hlspeed"===a&&(rspkr.c.data.settingsChanged=!0)},settingsChanged:!1,getSaveData:function(a,c){rspkr.log("[rspkr.c.data.getSaveData]");
a=a||"link";c=c||!1;var b=this.saveLink;if(!this.saveLink||this.settingsChanged||c){c&&rspkr.c.data.setParams(c);rspkr.c.data.params.customerid||(b=$rs.get("."+rspkr.cfg.item("ui.rsbtnClass")),(b=$rs.isArray(b)&&0<b.length?b[0]:b)&&rspkr.c.data.setParams($rs.getAttr($rs.findIn(b,".rsbtn_play"),"href")));var b={},d={audioformat:"mp3"};this.settingsChanged=!1;"iOS"!==this.browser.OS&&"dialog"===a&&(d.save="1");for(var e in this.params)this.params.hasOwnProperty(e)&&(b[e]=this.params[e]);for(e in d)d.hasOwnProperty(e)&&
(b[e]=d[e]);b.speed=r.speed(rspkr.st.get("hlspeed"),b.speed);0<this.selectedHTML.length?(this.setPostContent("textsel"),b=q.issuePost(b)):!0===rspkr.cfg.item("general.usePost")?(this.setPostContent("nosel"),b=q.issuePost(b)):b=s(b);c||(this.saveLink=b)}return b}},s=function(a){var c="";"undefined"!=typeof rspkr.cfg.item("general.servercall")?c=rspkr.cfg.item("general.servercall")+"?":(c=$rs.get("."+rspkr.cfg.item("ui.rsbtnClass")),c=$rs.isArray(c)?c[0]:c,c=$rs.getAttr($rs.findIn(c,".rsbtn_play"),
"href").split("?")[0]+"?");for(var b in a)a.hasOwnProperty(b)&&a[b]&&(c+=b+"="+a[b]+"&");c=c.substr(0,c.length-1);return rs.cfg.item("general.customProxy")?rs.cfg.item("general.customProxy")+encodeURIComponent(c):c},t=function(){var a=rspkr.cfg.item("extraMods")||[],c=[n.major,n.minor,n.update,n.revision].join("."),b=0,d="Explorer"==rs.c.data.browser.name&&8>=rs.c.data.browser.version;rspkr.log("[rspkr.c.loadExtraMods] Number of mod files to load: "+a.length);for(var e=0;e<a.length;e++){var f=a[e][0],
l=f.substring(f.lastIndexOf(".")),k=void 0;".js"===l?(k=document.createElement("script"),k.type="text/javascript",k.src=rs.params.path+"mods/"+f+"?v="+c,k.async=!0):".css"===l&&(f=rs.params.path+"mods/"+f+"?v="+c,d?k=document.createStyleSheet(f):(k=document.createElement("link"),k.type="text/css",k.rel="stylesheet",$rs.setAttr(k,"href",f)));d||void 0===k.onreadystatechange?k.onload=function(c){c&&"function"==typeof c&&c.apply(window);b++;b==a.length&&rs.devt("onAfterExtraModsLoaded",window)}(a[e][1]):
k.onreadystatechange=function(c){if("complete"==k.readyState||"loaded"==k.readyState)c&&"function"==typeof c&&c.apply(window),b++,b==a.length&&rs.devt("onAfterExtraModsLoaded",window)}(a[e][1]);d&&".css"===l||document.getElementsByTagName("head")[0].appendChild(k)}},g=function(a,c,b){if(p[a]){b=b||[];rspkr.displog[a]=rspkr.displog[a]?++rspkr.displog[a]:1;if(!p[a].length)return rspkr.log("[rspkr.c] Dispatched event: "+a+" - no handlers to call.",2),!0;rspkr.log("[rspkr.c] Dispatching event: "+a,1);
for(var d in p[a].reverse())if(p[a].hasOwnProperty(d)&&"function"==typeof p[a][d])try{"__self__"===c&&(c=p[a][d]),p[a][d].apply(c,b)}catch(e){rspkr.log("[rspkr.c._dispatchEvent] Error: "+e.message,3),this.isok=!1}else if("object"==typeof p[a][d])try{var f=p[a][d];f.func.apply(f.context||window,f.params||b)}catch(l){this.isok=!1}}else rspkr.log("[rspkr.c] Undefined event: "+a,3)},q={issuePost:function(a){rspkr.log("[rspkr.c] Using POST");document.getElementById("ReadSpeakerPostIframe"+rspkr.cfg.item("general.random"))||
this.createIframe();var c=Math.random(),b=this.createForm(a),d;a="undefined"!==typeof rspkr.cfg.item("general.servercall")?rspkr.cfg.item("general.servercall")+"?":function(){var a=$rs.get("."+rspkr.cfg.item("ui.rsbtnClass")),a=$rs.isArray(a)?a[0]:a;return $rs.getAttr($rs.findIn(a,".rsbtn_play"),"href").split("?")[0]+"?"}();d=("string"===typeof a&&a.length?a.split("/").pop():rspkr.pub.Config.item("general.rsent")).replace("?","");a=a&&a.match(/[^\/]*\/\/[^\/]*/);var e=rspkr.cfg.item("general.iframeproxy")?
rspkr.cfg.item("general.iframeproxy"):"/enterprise/iframeproxy.php";a=a?a.pop()+e+"?rsent="+d+"&version="+rspkr.pub.Config.item("general.proxyVersion"):rspkr.pub.Config.item("general.protocol")+"//"+rspkr.pub.Config.item("general.subdomain")+"."+rspkr.pub.Config.item("general.domain")+e+"?rsent="+rspkr.pub.Config.item("general.rsent")+"&version="+rspkr.pub.Config.item("general.proxyVersion");a+="&randid="+c;rspkr.c.data.params.customerid&&(a+="&customerid="+rspkr.c.data.params.customerid);a=rs.cfg.item("general.customProxy")?
rs.cfg.item("general.customProxy")+encodeURIComponent(a):a;b.action=a;d=document.createElement("textarea");1<h.getSelectedText().length?d.setAttribute("name","selectedhtml_base64"):d.setAttribute("name","html_base64");d.innerHTML=h.getPostContent();b.appendChild(d);setTimeout(function(){document.body.appendChild(b);b.submit();document.body.removeChild(b)},0);return a+"&listen=1&randid="+c},createForm:function(a){var c,b=document.createElement("form");b.target="ReadSpeakerPostIframe"+rspkr.cfg.item("general.random");
b.method="post";for(var d in a)c=document.createElement("input"),c.setAttribute("name",d),"url"===d?c.setAttribute("value",decodeURIComponent(a[d])):c.setAttribute("value",a[d]),b.appendChild(c);c=document.createElement("input");c.setAttribute("name","output");c.setAttribute("value","audiolink");b.appendChild(c);return b},createIframe:function(){if(!rspkr.cfg.item("general.random")){for(var a="",c=0;20>c;c++)a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*
Math.random()));rspkr.cfg.item("general.random",a)}a=null;if(document.selection)try{a=document.createElement('<iframe name="ReadSpeakerPostIframe'+rspkr.cfg.item("general.random")+'">')}catch(b){a=document.createElement("iframe")}else a=document.createElement("iframe");a.setAttribute("name","ReadSpeakerPostIframe"+rspkr.cfg.item("general.random"));a.setAttribute("id","ReadSpeakerPostIframe"+rspkr.cfg.item("general.random"));a.setAttribute("style","display: none; position: absolute;");a.setAttribute("sandbox",
"allow-scripts");a.style.display="none";var c=document.getElementsByTagName("body"),d=null;0<c.length&&(d=c.item(0));d&&d.appendChild(a)},removeIframe:function(){document.getElementById("ReadSpeakerPostIframe"+rspkr.cfg.item("general.random"))&&document.body.removeChild(document.getElementById("ReadSpeakerPostIframe"+rspkr.cfg.item("general.random")))}},m={encode:function(a){if("function"===typeof btoa)return btoa(encodeURIComponent(a).replace(/%([0-9A-F]{2})/g,function(a,b){return String.fromCharCode("0x"+
b)}));newdata=encodeURIComponent(a);var c=0,b=0;for(a=[];c<newdata.length;c++)37!=newdata.charCodeAt(c)?a[b]=newdata.charCodeAt(c):(a[b]=parseInt("0x"+newdata.charAt(c+1)+""+newdata.charAt(c+2)),c+=2),b++;c=a.length;parseInt((c+2)/3);for(var b=new String,d=parseInt(c/3),e,f=c-3*d,c=0;c<3*d;c+=3)e=this.chars(a[c]>>2),b+=e,e=this.chars((a[c]&3)<<4|a[c+1]>>4),b+=e,e=this.chars((a[c+1]&15)<<2|a[c+2]>>6),b+=e,e=this.chars(a[c+2]&63),b+=e;1==f&&(b+=this.chars(a[c]>>2),b+=this.chars((a[c]&3)<<4),b+="==");
2==f&&(b+=this.chars(a[c]>>2),b+=this.chars((a[c]&3)<<4|a[c+1]>>4),b+=this.chars((a[c+1]&15)<<2),b+="=");return b},decode:function(a){if("function"===typeof atob)return decodeURIComponent(atob(a).split("").map(function(a){return"%"+("00"+a.charCodeAt(0).toString(16)).slice(-2)}).join(""));for(var c="",b="",d=0,e=0,f="",l=a.length;d<l;)if(-1!=this.value(a[d])){for(var f=a.substring(d,d+4),k=e=0;4>k;k++)"="==f[k]&&e++;for(k=0;k<3-e;k++){0==k?b=this.value(f[0])<<2|(this.value(f[1])&48)>>4:1==k?b=(this.value(f[1])&
15)<<4|(this.value(f[2])&60)>>2:2==k&&(b=(this.value(f[2])&3)<<6|this.value(f[3]));var g=b.toString(16);1==g.length&&(g="0"+g);c+="%"+g}d+=4}else d++;return decodeURIComponent(c)},value:function(a){a=a.charCodeAt(0);return 65<=a&&90>=a?a-65:97<=a&&122>=a?a-97+26:48<=a&&57>=a?a-48+52:43==a?62:47==a?63:-1},chars:function(a){return 26>a?String.fromCharCode(a+65):52>a?String.fromCharCode(a+97-26):62>a?String.fromCharCode(a+48-52):62==a?"+":63==a?"/":String.fromCharCode(0)}};return{meta:n,init:function(){g("onInit",
window);p.onInit=[];p.onUIShowPlayer.push(rspkr.Common.data.setDefaultValues);p.onSettingsChanged.push(rspkr.Common.data.setSettingsChanged);p.onAfterModsLoaded.push(t)},addEvent:function(a,c){p[a].push(c)},base64:m,buildReadSpeakerCall:function(a){return s(a)},data:h,Detect:{init:function(){rspkr.log("[rspkr.c.Detect] Initialized!");var a=navigator.userAgent;h.browser.name=this.searchString(this.dataBrowser)||"Unknown";h.browser.version=this.searchVersion(a)||this.searchVersion(navigator.appVersion)||
"Unknown";h.browser.OS=this.searchString(this.dataOS)||"Unknown";h.browser.flashVersion=this.getFlashVersion();rspkr.log("[rspkr.c.Detect.init] Flash version: "+h.browser.flashVersion,1);"default"!==rspkr.pub.Config.item("general.syncContainer")?h.browser.syncContainer=rspkr.pub.Config.item("general.syncContainer"):h.browser.syncContainer="rs:span";a=h.browser.name;this.browserSettings.hasOwnProperty(h.browser.name)||(this.browserSettings[a]={});"default"===rspkr.pub.Config.item("general.syncContainer")&&
this.browserSettings[a].hasOwnProperty("syncContainer")&&(h.browser.syncContainer=this.browserSettings[a].syncContainer);this.browserSettings[a].hasOwnProperty("html5Support")?h.browser.html5Support=this.browserSettings[a].html5Support:document.createElement("audio").canPlayType&&(h.browser.html5Support=!0);if(!0===h.browser.html5Support){var c=document.createElement("audio"),b=!1,d=!1;c.canPlayType&&(b=!!c.canPlayType&&""!=c.canPlayType("audio/mpeg"),d=!!c.canPlayType&&""!=c.canPlayType('audio/ogg; codecs="vorbis"'));
rspkr.log("Browser can play mp3? "+c.canPlayType("audio/mpeg"),1);rspkr.log("Browser can play ogg? "+c.canPlayType('audio/ogg; codecs="vorbis"'),1);/android/i.test(rspkr.Common.data.browser.OS)&&b?h.browser.html5AudioFormat="mp3":/android/i.test(rspkr.Common.data.browser.OS)?h.browser.html5AudioFormat="ogg":!0===b?h.browser.html5AudioFormat="mp3":!0===d?h.browser.html5AudioFormat="ogg":h.browser.html5Support=!1;this.browserSettings[a].hasOwnProperty("html5Priority")?h.browser.html5Priority=this.browserSettings[a].priority:
h.browser.html5Priority=!0;this.browserSettings[a].hasOwnProperty("audioFormat")&&(h.browser.html5AudioFormat=this.browserSettings[a].audioFormat)}this.browserSettings[a].hasOwnProperty("minver")&&parseFloat(h.browser.version)<=parseFloat(this.browserSettings[a].minver)&&(h.browser.html5Priority=!1)},browserSettings:{Android:{minver:4},Explorer:{syncContainer:"font"},Firefox:{minver:6},Opera:{html5Support:!1,priority:!1},Edge:{audioFormat:"mp3"}},getFlashVersion:function(){try{if(document.selection){try{var a=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");try{a.AllowScriptAccess="always"}catch(c){return"6,0,0"}}catch(b){}return(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}try{if(navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(d){}}catch(e){try{if(navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)return(navigator.plugins["Shockwave Flash 2.0"]||
navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(f){}}return"0,0,0"},searchString:function(a){for(var c=0;c<a.length;c++){var b=a[c].string,d=a[c].prop;this.versionSearchString=a[c].versionSearch||a[c].identity;if(b){if(-1!=b.indexOf(a[c].subString))return a[c].identity}else if(d)return a[c].identity}},searchVersion:function(a){var c=a.indexOf(this.versionSearchString);if(-1!=c)return parseFloat(a.substring(c+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,
subString:"Edge",identity:"Edge"},{string:navigator.userAgent,subString:"Chromium",identity:"Chromium"},{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera",versionSearch:"Version"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",
identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Trident",identity:"Explorer",versionSearch:"Trident"},{string:navigator.userAgent,subString:"Android",identity:"Android"},{string:navigator.userAgent,subString:"Gecko",
identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:navigator.platform,subString:"ARM",identity:"Windows Phone"},{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iOS"},{string:navigator.userAgent,subString:"iPad",identity:"iOS"},{string:navigator.userAgent,subString:"Android",
identity:"Android"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]},dispatchEvent:function(a,c,b){g(a,c,b)},post:q,cookie:{create:function(a,c,b,d,e){b=b||rspkr.pub.Config.item("general.cookieLifetime");d=d||rspkr.pub.Config.item("general.cookiePath");e=e||rspkr.pub.Config.item("general.cookieDomain");if(b){var f=new Date;f.setTime(f.getTime()+b);b="; expires="+f.toGMTString()}else b="";a=a+"="+c+b+(d?"; path="+d:"")+(e?"; domain="+e:"");a="https:"===document.location.protocol?a+
"; SameSite=None; Secure":a+"; SameSite=Lax";return document.cookie=a},read:function(a){a+="=";for(var c=document.cookie.split(";"),b=0;b<c.length;b++){for(var d=c[b];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,d.length)}},readKey:function(a,c){var b=this.read(a),d;if(b)for(var b=b.split("&"),e=0,f=b.length;e<f;e++)if(d=b[e].split("="),d[0]==c)return d[1]},readKeyAll:function(a){a=this.read(a);var c={},b;if(a){a=a.split("&");for(var d=0,e=a.length;d<
e;d++)b=a[d].split("="),c[b[0]]=b[1];return c}},createSub:function(a,c,b,d,e){if("object"!==typeof c)this.create(a,c.toString(),b,d,e);else{var f=[],l;for(l in c)f.push(l+"="+c[l]);return this.create(a,f.join("&"),b,d,e)}},updateKey:function(a,c,b,d,e,f){b=b.toString();for(var l=decodeURIComponent(this.read(a)),g,h={},q=!1,l=l&&"null"!=l&&"undefined"!=l?-1<l.indexOf("=")&&-1==l.indexOf("&")?[l]:l.split("&"):[],m=0,n=l.length;m<n;m++)g=l[m].split("="),g[0]==c&&(g[1]=b,q=!0),g.length&&g[1].length&&
(h[g[0]]=g[1]);!q&&b.length&&(h[c]=b);return this.createSub(a,h,d,e,f)},erase:function(a,c,b){this.create(a,"",-1,c,b)}},css:{getStylesheet:function(a,c){if(void 0===c||null===c)c=document;var b;(b=c.styleSheets[a]||c.getElementById(a))||(b=c.createElement("style"),b.type="text/css",b.id=b.name=a,(c.getElementsByTagName("head")[0]||c.body).appendChild(b),b.addRule||b.sheet||(b=c.styleSheets[a]));return b.sheet||b},rsSheet:function(a){try{this.rules=a.rules||a.cssRules}catch(c){this.rules=a.cssRules}this.del=
function(a,c){a.deleteRule?a.deleteRule(c):a.removeRule&&a.removeRule(c)};this.ins=function(a,c,e){$rs.isArray(e)||(e=[e]);if(a.insertRule&&a.cssRules)a.insertRule(c+" {"+e.join(";")+";}",a.cssRules.length);else if(a.addRule)for(var f=0,g=e.length;f<g;f++)a.addRule(c,e[f])}},setRule:function(a,c,b){function d(a,b){if(void 0===b||null===b)b=[];var c=[];try{c=a.document.querySelectorAll("iframe, frame")}catch(e){}for(var f=0;f<c.length;f++)b.push(c[f].contentWindow);for(f=0;f<c.length;f++)d(c[f].contentWindow,
b)}var e=[],f=[];f.push(document);if(rspkr.cfg.item("general.iframeReading")){d(window,e);for(var g=0;g<e.length;g++)try{null!==e[g]&&void 0!==e[g]&&null!==e[g].document&&f.push(e[g].document)}catch(h){}}for(e=g=0;e<f.length;e++){var g=this.getStylesheet(a,f[e]),q=new this.rsSheet(g);q.ins(g,c,"string"==typeof b?b.split(";"):b);g=q.length}return g},removeRule:function(a,c,b){a=this.getStylesheet(a,b);b=new this.rsSheet(a);var d=[];if(b.rules){for(var e=0,f=b.rules.length;e<f;e++)b.rules[e].selectorText==
c&&d.push(e);for(;d.length;)b.del(a,d.pop());return d}return b},replaceRule:function(a,c,b){this.removeRule(a,c);this.setRule(a,c,b)}},converter:r,findFirstRSButton:function(a){a=$rs.get("a, .rsbtn_play");a=$rs.isArray(a)?a:[a];for(var c=0,b=a.length;c<b;c++)if($rs.hasClass(a[c],"rsbtn_play")||$rs.getAttr(a[c],"href")&&-1!==$rs.getAttr(a[c],"href").indexOf(rspkr.pub.Config.item("general.domain")+"/cgi-bin/"+rspkr.pub.Config.item("general.rsent"))||$rs.getAttr(a[c],"href")&&/customerid=/i.test($rs.getAttr(a[c],
"href"))&&/lang=/i.test($rs.getAttr(a[c],"href"))&&/(readid|readclass)/i.test($rs.getAttr(a[c],"href")))return a[c];return!1},decodeEntities:function(a){var c=document.createElement("p");c.innerHTML=a;return c.textContent||c.innerText},e:p,createShortcuts:function(){var a=window.ReadSpeaker;a.Common&&(a.c=a.Common);a.c&&(a.evt=a.c.addEvent,a.devt=a.c.dispatchEvent);a.c&&a.c.Settings&&(a.c.s=a.c.Settings);a.c.s&&(a.st=a.c.s);a.lib&&(a.l=a.lib);a.l&&a.lib.Facade&&(a.l.f=a.lib.Facade);a.l&&a.l.f&&a.l.f.adapter&&
(a.l.f.a=a.l.f.adapter);a.modmap&&(a.m=a.modmap);a.pub&&a.pub.Config&&(a.pub.c=a.pub.Config);a.pub.c&&(a.cfg=a.pub.c);a.PlayerAPI&&(a.pl=a.PlayerAPI);a.HL&&(a.hl=a.HL);a.ui&&(a.u=a.ui)}}}();rspkr.lib||(rspkr.lib={});
rspkr.lib.Facade=function(n){var p=function(g,h,m){g=String(g);m=String(m);h="="==h?"==":h;g=g.split(".");m=m.split(".");for(var a=Math.max(g.length,m.length),c,b,d=0,e=0;e<a&&!d;e++)c=parseInt(g[e],10)||0,b=parseInt(m[e],10)||0,c<b&&(d=1),c>b&&(d=-1);switch(h){case "==":return 0==d;case "===":return 0===d;case "!=":return 0!=d;case "!==":return 0!==d;case "<":return 0<d;case "<=":return 0<=d;case ">":return 0>d;case ">=":return 0>=d;default:return!1}},r=[{name:"jquery",minver:"1.4.1",check:function(){if("function"==
typeof jQuery){if("explorer"===rspkr.Common.data.browser.name.toLowerCase()&&9>rspkr.Common.data.browser.version&&p(jQuery.fn.jquery,"<",2))return!1;if(p(jQuery.fn.jquery,">=",this.minver))return!0}return!1}}],h="",s=function(){n.$rs.flatten=function(g,h){$rs.isArray(g)||(g=[g]);h=h||[];for(var m=0,a;a=g[m];m++)$rs.isArray(a)?$rs.flatten(a,h):h.push(a);return h}},t={store:[],push:function(g,h,m){this.store[g]||(this.store[g]=[]);this.store[g][h]||(this.store[g][h]=[]);this.store[g][h].push(m);return this.store.length},
pop:function(g,h,m){var a;if(this.store[g]&&this.store[g][h]){a=this.store[g][h];if(!m)return this.store[g][h].splice(0,this.store[g][h].length),0;for(var c=a.length-1;-1<c;c--)a[c].toString()==m.toString()&&this.store[g][h].splice(c,1);return this.store[g][h].length}return 0},dispatch:function(g,h){var m=$rs.convertEvent(g,h);if(rsid=$rs.getAttr(m.target,"data-rsevent-id")){for(var a=!0,c=t.store[rsid][m.type],b=0,d=c.length;b<d;b++)"function"==typeof c[b]&&(c[b].apply(m.target,[m])||(a=!1));return a}}};
return{init:function(){if(rspkr&&rspkr.params&&rspkr.params.forceRSLib&&"1"===rspkr.params.forceRSLib)h="RSLib";else{for(idx in r)if(r[idx]&&r[idx].check&&r[idx].check()){h=r[idx].name;break}h.length||(h="RSLib")}},currentLib:function(){return h},setLib:function(g){h=g},eq:t,adapterInit:function(g){n.$rs=g;s()}}}(window);ReadSpeaker.lib.Facade.RSEvent=function(){};
ReadSpeaker.modmap={products:{all:[],custom:function(){var n=[];n.push(["Custom","text/javascript"]);return n},dr:function(){var n=[];n.push(["DocReader.AutoAdd","text/javascript"]);return n},expl:function(){var n=this.all;n.push(["PlayerAPI","text/javascript"],["XP","text/javascript"],["ui","text/javascript",["ui","ui.Lightbox","ui.Slider"]]);return n},embhl:function(){var n=this.all;n.push(["Base","text/javascript","PlayerAPI HL ui ui.Lightbox ui.Slider Common.Settings".split(" ")]);return n}}};
